// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW3OUfryUaCjTyPPoChwhkmJuIv-2xyrI',
    appId: '1:351752559333:web:ba52f8b038bdf90bcf920c',
    messagingSenderId: '351752559333',
    projectId: 'fier-master',
    authDomain: 'fier-master.firebaseapp.com',
    storageBucket: 'fier-master.appspot.com',
    measurementId: 'G-MD3YNDD0PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDORIGRYcn3AlUMUoszKuE024opXIyIrUc',
    appId: '1:351752559333:android:d7c01d2e33cfb578cf920c',
    messagingSenderId: '351752559333',
    projectId: 'fier-master',
    storageBucket: 'fier-master.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnDa814bfUZVl5u4LGokJ_WvrRPm1_skw',
    appId: '1:351752559333:ios:873f22f174b1334acf920c',
    messagingSenderId: '351752559333',
    projectId: 'fier-master',
    storageBucket: 'fier-master.appspot.com',
    iosClientId: '351752559333-ic1dgdgch00gu5iqm4qv6881nivkasnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnDa814bfUZVl5u4LGokJ_WvrRPm1_skw',
    appId: '1:351752559333:ios:873f22f174b1334acf920c',
    messagingSenderId: '351752559333',
    projectId: 'fier-master',
    storageBucket: 'fier-master.appspot.com',
    iosClientId: '351752559333-ic1dgdgch00gu5iqm4qv6881nivkasnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireBase',
  );
}
